"""Interactive post-call summary review helpers."""

from __future__ import annotations

import json
import shutil
import sys
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any

SUMMARY_REVIEW_FILENAME = "summary_review.json"
GENERATED_SUMMARY_FILENAME = "summary.generated.md"


def summary_review_path(session_dir: Path) -> Path:
    """Return the persisted summary review metadata path for a session."""
    return session_dir / SUMMARY_REVIEW_FILENAME


def generated_summary_path(session_dir: Path) -> Path:
    """Return the raw generated-summary path for a session."""
    return session_dir / GENERATED_SUMMARY_FILENAME


def load_summary_review(session_dir: Path) -> dict[str, Any] | None:
    """Load persisted summary-review metadata if present."""
    path = summary_review_path(session_dir)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _split_footer(text: str) -> tuple[str, str]:
    marker = "\n\n---\n*Generated by Scarecrow"
    idx = text.find(marker)
    if idx == -1:
        return text.rstrip(), ""
    return text[:idx].rstrip(), text[idx:]


def _load_summary_parts(summary_path: Path) -> tuple[str, str]:
    text = summary_path.read_text(encoding="utf-8")
    return _split_footer(text)


def _display_summary_body(body: str) -> str:
    """Hide Action Items during summary review to keep phases separate."""
    return body.split("\n## Action Items\n", 1)[0].rstrip()


def _save_summary_review(session_dir: Path, *, status: str) -> Path:
    payload = {
        "reviewed_at": datetime.now().isoformat(timespec="seconds"),
        "status": status,
    }
    path = summary_review_path(session_dir)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path


def _copy_generated_summary(summary_path: Path) -> Path:
    session_dir = summary_path.parent
    generated_path = generated_summary_path(session_dir)
    shutil.copy2(summary_path, generated_path)
    return generated_path


def prompt_for_summary_review(
    summary_path: Path,
    *,
    input_fn: Callable[[str], str] = input,
    print_fn: Callable[..., None] = print,
    regenerate_fn: Callable[[str | None], Path | None] | None = None,
) -> bool:
    """Prompt the user to validate or edit the generated summary.

    Returns True when the summary was explicitly reviewed/rewritten, False when
    canceled or unavailable. The raw model output is copied to
    ``summary.generated.md`` before any edits.
    """
    if not sys.stdin.isatty():
        return False
    if not summary_path.exists():
        return False

    body, _footer = _load_summary_parts(summary_path)
    _copy_generated_summary(summary_path)

    print_fn()
    print_fn("  Summary review")
    print_fn("  --------------")
    print_fn(_display_summary_body(body))
    print_fn()
    print_fn("  Options: [a]ccept, [e]dit via feedback")

    while True:
        try:
            choice = input_fn("  Choice: ").strip().lower() or "a"
        except KeyboardInterrupt:
            print_fn()
            print_fn("  Summary review canceled.")
            _save_summary_review(summary_path.parent, status="canceled")
            return False
        if choice in {"a", "accept"}:
            _save_summary_review(summary_path.parent, status="accepted")
            return True
        if choice in {"e", "edit"}:
            if regenerate_fn is None:
                print_fn("  Feedback-driven edit is unavailable for this run.")
                continue
            print_fn("  Describe factual errors, missing details, or changes to make.")
            print_fn("  Press Enter on a blank line when finished.")
            lines: list[str] = []
            while True:
                try:
                    line = input_fn("    > ")
                except KeyboardInterrupt:
                    print_fn()
                    print_fn("  Summary feedback canceled.")
                    _save_summary_review(summary_path.parent, status="canceled")
                    return False
                if not line.strip():
                    break
                lines.append(line)
            feedback = "\n".join(lines).strip()
            if not feedback:
                print_fn("  Empty feedback ignored.")
                continue
            regenerated = regenerate_fn(feedback)
            if regenerated is None or not regenerated.exists():
                print_fn("  Regenerate failed; keeping current draft.")
                continue
            summary_path = regenerated
            body, _footer = _load_summary_parts(summary_path)
            _copy_generated_summary(summary_path)
            _save_summary_review(summary_path.parent, status="edited-via-feedback")
            print_fn()
            print_fn("  Updated summary")
            print_fn("  ---------------")
            print_fn(_display_summary_body(body))
            print_fn()
            print_fn("  Options: [a]ccept, [e]dit via feedback")
            continue
        print_fn("  Invalid choice. Use a or e.")
