"""Interactive post-call task review helpers."""

from __future__ import annotations

import json
import re
import sys
from collections.abc import Callable
from datetime import datetime
from pathlib import Path
from typing import Any

from scarecrow import config

TASK_REVIEW_FILENAME = "task_review.json"


def task_review_path(session_dir: Path) -> Path:
    """Return the persisted task review path for a session."""
    return session_dir / TASK_REVIEW_FILENAME


def load_task_review(session_dir: Path) -> dict[str, Any] | None:
    """Load a persisted task review if present."""
    path = task_review_path(session_dir)
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def load_reviewed_tasks(session_dir: Path) -> list[str] | None:
    """Return reviewed task texts, or None if no review exists."""
    review = load_task_review(session_dir)
    if review is None:
        return None
    tasks = review.get("tasks", [])
    return [
        task.get("text", "").strip() for task in tasks if task.get("text", "").strip()
    ]


def save_task_review(session_dir: Path, tasks: list[dict[str, Any]]) -> Path:
    """Persist reviewed tasks for reuse by later reprocess runs."""
    payload = {
        "reviewed_at": datetime.now().isoformat(timespec="seconds"),
        "tasks": tasks,
    }
    path = task_review_path(session_dir)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path


def collect_task_candidates(
    session_dir: Path, summary_path: Path
) -> list[dict[str, Any]]:
    """Return merged task candidates from explicit notes and summary output."""
    merged: dict[str, dict[str, Any]] = {}

    for item in _extract_explicit_task_notes(session_dir):
        normalized = item["normalized"]
        if not normalized:
            continue
        merged[normalized] = {
            "text": item["text"],
            "normalized": normalized,
            "sources": ["explicit"],
        }

    for item in _extract_action_item_details(summary_path):
        normalized = item["normalized"]
        if not normalized:
            continue
        entry = merged.setdefault(
            normalized,
            {
                "text": item["text"],
                "normalized": normalized,
                "sources": [],
            },
        )
        if "generated" not in entry["sources"]:
            entry["sources"].append("generated")
        if not entry["text"].strip():
            entry["text"] = item["text"]

    return list(merged.values())


def rewrite_summary_action_items(summary_path: Path, tasks: list[str]) -> None:
    """Replace the Action Items section in summary.md with reviewed tasks."""
    try:
        text = summary_path.read_text(encoding="utf-8")
    except OSError:
        return

    footer_match = re.search(r"\n\n---\n\*Generated by Scarecrow.*\Z", text, re.DOTALL)
    if footer_match:
        body = text[: footer_match.start()]
        footer = text[footer_match.start() :]
    else:
        body = text
        footer = ""

    section_pattern = re.compile(r"(?ms)^## Action Items\n.*?(?=^## |\Z)")
    body = section_pattern.sub("", body).rstrip()

    if tasks:
        section_lines = ["## Action Items", ""]
        section_lines.extend(f"- [ ] {task}" for task in tasks)
        section = "\n".join(section_lines)
        body = f"{body}\n\n{section}" if body else section

    summary_text = body.rstrip()
    if footer:
        summary_text = f"{summary_text}{footer}"
    else:
        summary_text += "\n"
    summary_path.write_text(summary_text, encoding="utf-8")


def _collect_feedback_lines(
    *,
    input_fn: Callable[[str], str],
    print_fn: Callable[..., None],
    prompt: str,
) -> list[str] | None:
    """Collect freeform feedback lines ending with a blank line."""
    print_fn(prompt)
    print_fn("  Press Enter on a blank line when finished.")
    lines: list[str] = []
    while True:
        try:
            line = input_fn("    > ")
        except KeyboardInterrupt:
            print_fn()
            print_fn("  Task review canceled.")
            return None
        if not line.strip():
            break
        lines.append(line)
    return [line.strip() for line in lines if line.strip()]


def _refine_tasks_with_feedback(
    tasks: list[dict[str, Any]],
    feedback_lines: list[str],
    *,
    print_fn: Callable[..., None],
) -> list[dict[str, Any]]:
    """Use the local LLM to revise the task list from freeform feedback."""
    from scarecrow.summarizer import (
        _compute_ctx_size,
        _create_backend,
        _estimate_tokens,
    )

    task_lines = [
        f"{idx}. {item['text']} [{'+'.join(sorted(item['sources'])) or 'generated'}]"
        for idx, item in enumerate(tasks, start=1)
    ]
    feedback_text = "\n".join(f"- {line}" for line in feedback_lines)
    system_prompt = (
        "Revise the task list based on the user's feedback.\n\n"
        "Rules:\n"
        "- Output ONLY Markdown checkbox lines in the form `- [ ] task text`.\n"
        "- Keep valid tasks, remove tasks the user says are wrong, and rewrite task "
        "wording when the user clarifies the intent.\n"
        "- Add tasks only when the user explicitly asks to add them.\n"
        "- Do not invent new tasks.\n"
        "- Preserve concrete nouns, names, and acronyms when the user corrects them.\n"
        "- If no tasks remain, output exactly `NONE`.\n"
    )
    user_content = (
        "Current tasks:\n"
        f"{chr(10).join(task_lines) if task_lines else 'NONE'}\n\n"
        "User feedback:\n"
        f"{feedback_text}\n"
    )

    input_tokens = _estimate_tokens(system_prompt + user_content)
    ctx_size = _compute_ctx_size(input_tokens)
    be = _create_backend(config.SUMMARIZER_BACKEND, ctx_size=ctx_size)
    print_fn(f"  Applying task feedback with {be.name}…")
    be.load()
    try:
        raw_text, _tokens = be.generate(system_prompt, user_content)
    finally:
        be.close()

    text = raw_text.strip()
    if text.upper() == "NONE":
        return []

    revised: list[dict[str, Any]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if not stripped.startswith("- ["):
            continue
        task_text = re.sub(r"^- \[[ xX]\]\s*", "", stripped).strip()
        if not task_text:
            continue
        revised.append(
            {
                "text": task_text,
                "normalized": _normalize_action_item(task_text),
                "sources": ["reviewed"],
            }
        )

    deduped: dict[str, dict[str, Any]] = {}
    for item in revised:
        normalized = item["normalized"]
        if not normalized:
            continue
        deduped[normalized] = item
    result = list(deduped.values())
    result.sort(key=lambda item: item["text"].casefold())
    return result


def prompt_for_task_review(
    session_dir: Path,
    summary_path: Path,
    *,
    input_fn: Callable[[str], str] = input,
    print_fn: Callable[..., None] = print,
) -> list[str] | None:
    """Prompt the user to review tasks and rewrite summary.md if confirmed."""
    if not sys.stdin.isatty():
        return None

    candidates = collect_task_candidates(session_dir, summary_path)
    print_fn()
    print_fn("  Task review")
    print_fn("  -----------")
    if not candidates:
        print_fn("  No tasks were detected automatically.")
    working = list(candidates)

    while True:
        if working:
            for idx, item in enumerate(working, start=1):
                sources = "+".join(sorted(item["sources"])) or "generated"
                print_fn(f"  {idx}. {item['text']} [{sources}]")
        print_fn()
        print_fn("  Options: [a]ccept, [e]dit via feedback")
        try:
            choice = input_fn("  Choice: ").strip().lower() or "a"
        except KeyboardInterrupt:
            print_fn()
            print_fn("  Task review canceled.")
            return None
        if choice in {"a", "accept"}:
            save_task_review(session_dir, working)
            rewrite_summary_action_items(
                summary_path, [item["text"] for item in working]
            )
            print_fn(f"  Saved {len(working)} reviewed task(s).")
            print_fn()
            return [item["text"] for item in working]
        if choice in {"e", "edit"}:
            feedback_lines = _collect_feedback_lines(
                input_fn=input_fn,
                print_fn=print_fn,
                prompt=(
                    "  Describe task corrections, removals, or additions "
                    "in plain text.\n"
                    "  Examples: `drop 3`, `2 is verify combo check contact info`, "
                    "`add email Marymount after checking benefits`"
                ),
            )
            if feedback_lines is None:
                return None
            if not feedback_lines:
                print_fn("  Empty feedback ignored.")
                continue
            try:
                working = _refine_tasks_with_feedback(
                    working,
                    feedback_lines,
                    print_fn=print_fn,
                )
            except Exception:
                print_fn("  Task refinement failed; keeping the current task list.")
                continue
            print_fn()
            print_fn("  Updated tasks")
            print_fn("  -------------")
            if not working:
                print_fn("  No remaining tasks.")
            continue
        print_fn("  Invalid choice. Use a or e.")


def _normalize_action_item(text: str) -> str:
    normalized = text.casefold().strip()
    normalized = re.sub(r"^[\-\*\d\.\)\s]+", "", normalized)
    normalized = re.sub(r"[^\w\s]", " ", normalized)
    normalized = re.sub(r"\s+", " ", normalized)
    return normalized.strip()


def _extract_action_item_details(summary_md: Path) -> list[dict[str, str]]:
    if not summary_md.exists():
        return []
    try:
        text = summary_md.read_text(encoding="utf-8")
    except OSError:
        return []

    items: list[dict[str, str]] = []
    for match in re.finditer(
        r"^## Action Items\n(.*?)(?=^##|\Z)", text, re.M | re.DOTALL
    ):
        for line in match.group(1).splitlines():
            stripped = line.strip()
            if not stripped.startswith("- ["):
                continue
            item_text = re.sub(r"^- \[[ xX]\]\s*", "", stripped).strip()
            items.append(
                {
                    "text": item_text,
                    "normalized": _normalize_action_item(item_text),
                }
            )
    return items


def _extract_explicit_task_notes(session_dir: Path) -> list[dict[str, str]]:
    transcript = session_dir / "transcript.jsonl"
    if not transcript.exists():
        return []

    items: list[dict[str, str]] = []
    try:
        with transcript.open(encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    event = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if event.get("type") != "note":
                    continue
                if event.get("tag", "").upper() != "TASK":
                    continue
                text = event.get("text", "").strip()
                if not text:
                    continue
                items.append(
                    {
                        "text": text,
                        "normalized": _normalize_action_item(text),
                    }
                )
    except OSError:
        return []

    return items
