"""Tests for summary review helpers."""

from __future__ import annotations

from pathlib import Path

from scarecrow.summary_review import (
    generated_summary_path,
    load_summary_review,
    prompt_for_summary_review,
)


def test_prompt_for_summary_review_accepts_and_copies_generated(
    tmp_path: Path, monkeypatch
) -> None:
    summary = tmp_path / "summary.md"
    summary.write_text(
        "## Summary\n\nDraft summary.\n\n## Key Points\n- Point\n\n---\n"
        "*Generated by Scarecrow · footer*\n",
        encoding="utf-8",
    )
    responses = iter(["a"])
    monkeypatch.setattr("sys.stdin.isatty", lambda: True)

    reviewed = prompt_for_summary_review(
        summary,
        input_fn=lambda _: next(responses),
        print_fn=lambda *args, **kwargs: None,
    )

    assert reviewed is True
    assert generated_summary_path(tmp_path).exists()
    assert load_summary_review(tmp_path)["status"] == "accepted"


def test_prompt_for_summary_review_edits_via_feedback(
    tmp_path: Path, monkeypatch
) -> None:
    summary = tmp_path / "summary.md"
    summary.write_text(
        "## Summary\n\nDraft summary.\n\n## Key Points\n- Point\n\n---\n"
        "*Generated by Scarecrow · footer*\n",
        encoding="utf-8",
    )
    responses = iter(["e", "The benefits timeline is wrong.", "", "a"])
    seen_feedback: list[str | None] = []
    monkeypatch.setattr("sys.stdin.isatty", lambda: True)

    def _regenerate(feedback: str | None) -> Path:
        seen_feedback.append(feedback)
        summary.write_text(
            "## Summary\n\nReviewed summary.\n\n## Key Points\n- Point\n\n---\n"
            "*Generated by Scarecrow · footer*\n",
            encoding="utf-8",
        )
        return summary

    reviewed = prompt_for_summary_review(
        summary,
        input_fn=lambda _: next(responses),
        print_fn=lambda *args, **kwargs: None,
        regenerate_fn=_regenerate,
    )

    assert reviewed is True
    assert seen_feedback == ["The benefits timeline is wrong."]
    content = summary.read_text(encoding="utf-8")
    assert "Reviewed summary." in content
    assert "Generated by Scarecrow" in content
    assert load_summary_review(tmp_path)["status"] == "accepted"


def test_prompt_for_summary_review_rejects_removed_regenerate_option(
    tmp_path: Path, monkeypatch
) -> None:
    summary = tmp_path / "summary.md"
    summary.write_text(
        "## Summary\n\nFirst draft.\n\n---\n*Generated by Scarecrow · footer*\n",
        encoding="utf-8",
    )
    responses = iter(["r", "a"])
    printed: list[str] = []
    monkeypatch.setattr("sys.stdin.isatty", lambda: True)

    reviewed = prompt_for_summary_review(
        summary,
        input_fn=lambda _: next(responses),
        print_fn=lambda *args, **kwargs: printed.append(
            " ".join(str(arg) for arg in args)
        ),
    )

    assert reviewed is True
    assert any("Invalid choice. Use a or e." in line for line in printed)
    assert load_summary_review(tmp_path)["status"] == "accepted"


def test_prompt_for_summary_review_cancels_cleanly_on_ctrl_c(
    tmp_path: Path, monkeypatch
) -> None:
    summary = tmp_path / "summary.md"
    summary.write_text("## Summary\n\nDraft.\n", encoding="utf-8")
    monkeypatch.setattr("sys.stdin.isatty", lambda: True)

    class _InterruptOnce:
        def __init__(self) -> None:
            self.calls = 0

        def __call__(self, _prompt: str) -> str:
            self.calls += 1
            raise KeyboardInterrupt

    interrupted = _InterruptOnce()

    reviewed = prompt_for_summary_review(
        summary,
        input_fn=interrupted,
        print_fn=lambda *args, **kwargs: None,
    )

    assert reviewed is False
    assert interrupted.calls == 1
    assert load_summary_review(tmp_path)["status"] == "canceled"
