"""Tests for task review helpers."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

from scarecrow.task_review import (
    collect_task_candidates,
    load_reviewed_tasks,
    prompt_for_task_review,
    rewrite_summary_action_items,
    save_task_review,
)


def _write_transcript(session_dir: Path, events: list[dict]) -> None:
    transcript = session_dir / "transcript.jsonl"
    transcript.write_text(
        "\n".join(json.dumps(event) for event in events) + "\n",
        encoding="utf-8",
    )


def test_collect_task_candidates_merges_explicit_and_generated(tmp_path: Path) -> None:
    _write_transcript(
        tmp_path,
        [
            {"type": "note", "tag": "TASK", "text": "Send recap"},
        ],
    )
    summary = tmp_path / "summary.md"
    summary.write_text(
        "## Summary\nMeeting.\n\n"
        "## Action Items\n- [ ] Send recap\n- [ ] Review contract\n",
        encoding="utf-8",
    )

    candidates = collect_task_candidates(tmp_path, summary)

    assert len(candidates) == 2
    assert any(item["text"] == "Send recap" for item in candidates)
    assert any(item["text"] == "Review contract" for item in candidates)
    send_recap = next(item for item in candidates if item["text"] == "Send recap")
    assert send_recap["sources"] == ["explicit", "generated"]


def test_rewrite_summary_action_items_replaces_section(tmp_path: Path) -> None:
    summary = tmp_path / "summary.md"
    summary.write_text(
        "## Summary\nA short summary.\n\n"
        "## Key Points\n- Point\n\n"
        "## Action Items\n- [ ] Old task\n\n"
        "---\n*Generated by Scarecrow*\n",
        encoding="utf-8",
    )

    rewrite_summary_action_items(summary, ["New task", "Another task"])
    content = summary.read_text(encoding="utf-8")

    assert "- [ ] New task" in content
    assert "- [ ] Another task" in content
    assert "Old task" not in content
    assert "Generated by Scarecrow" in content


def test_prompt_for_task_review_persists_selection_and_additions(
    tmp_path: Path, monkeypatch
) -> None:
    _write_transcript(
        tmp_path,
        [
            {"type": "note", "tag": "TASK", "text": "Send recap"},
        ],
    )
    summary = tmp_path / "summary.md"
    summary.write_text(
        "## Summary\nMeeting.\n\n"
        "## Action Items\n- [ ] Send recap\n- [ ] Review contract\n\n"
        "---\n*Generated by Scarecrow*\n",
        encoding="utf-8",
    )

    responses = iter(
        [
            "e",
            '2 is verify "combo check" contact info with veterans@marymount.edu',
            "add Follow up with admissions after benefits review",
            "",
            "a",
        ]
    )
    monkeypatch.setattr("sys.stdin.isatty", lambda: True)

    with patch(
        "scarecrow.task_review._refine_tasks_with_feedback",
        return_value=[
            {
                "text": "Follow up with admissions after benefits review",
                "normalized": "follow up with admissions after benefits review",
                "sources": ["reviewed"],
            },
            {
                "text": "Send recap",
                "normalized": "send recap",
                "sources": ["reviewed"],
            },
            {
                "text": 'verify "combo check" contact info with veterans@marymount.edu',
                "normalized": (
                    "verify combo check contact info with veterans marymount edu"
                ),
                "sources": ["reviewed"],
            },
        ],
    ):
        selected = prompt_for_task_review(
            tmp_path,
            summary,
            input_fn=lambda _: next(responses),
            print_fn=lambda *args, **kwargs: None,
        )

    assert selected == [
        "Follow up with admissions after benefits review",
        "Send recap",
        'verify "combo check" contact info with veterans@marymount.edu',
    ]
    assert load_reviewed_tasks(tmp_path) == [
        "Follow up with admissions after benefits review",
        "Send recap",
        'verify "combo check" contact info with veterans@marymount.edu',
    ]
    content = summary.read_text(encoding="utf-8")
    assert "- [ ] Send recap" in content
    assert "- [ ] Follow up with admissions after benefits review" in content
    assert (
        '- [ ] verify "combo check" contact info with veterans@marymount.edu' in content
    )
    assert "Review contract" not in content


def test_save_task_review_can_persist_empty_review(tmp_path: Path) -> None:
    save_task_review(tmp_path, [])
    assert load_reviewed_tasks(tmp_path) == []
